language: php
php:
    - 7.0
    - 7.1
    - 7.2
    - 7.3
    - 7.4snapshot
    - nightly
matrix:
    allow_failures:
        - php: nightly
        - php: 7.4snapshot
install:
    - sudo apt-get update
    - sudo apt-get install -y valgrind
script:
    - phpize
    - wget -q -O run-tests.php https://raw.githubusercontent.com/php/php-src/master/run-tests.php
    - ./configure
    - make
    - REPORT_EXIT_STATUS=1 TEST_PHP_ARGS="-m --show-mem -q --show-diff" make test
